# server
server:
  port: 8080
# spring
spring:
  servlet:
    multipart:
      # 文件上传大小限制
      max-file-size: 500MB
      max-request-size: 500MB
  # 数据源
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/upms?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456

dromara:
  # 文件存储
  x-file-storage:
    default-platform: local-plus-1
    thumbnail-suffix: ".min.jpg"
    local-plus:
      - platform: local-plus-1
        enable-storage: true
        base-path: test/
        storage-path: D:/temp/
    ftp:
      - platform: ftp-1
        enable-storage: true
        host: 192.168.3.165
        port: 2367
        user: ftpadmin
        password: 123456
        base-path: filestorage
        pool:
          # 对象空闲超过此时间将逐出（注：没有配置此项时，实际使用一段时间后，池中出现有问题的客户端对象，上传不了文件，但没有报错）
          minEvictableIdleDuration: 5M
    webdav:
      - platform: webdav-1
        enable-storage: true
        server: http://127.0.0.1:5244/
        user: admin
        password: 123456
        base-path: dav/zwb/
    minio:
      - platform: minio-1
        enable-storage: true
        accessKey: "Q4EORZGwSV6SwDC500i8"
        secretKey: "RF0wsFogD92Uas78PVNppfUmtPAvUsGV9Z4s7qKz"
        endPoint: "http://127.0.0.1:9000"
        bucketName: "test"
